[package]
name = "miri"
version = "0.0.0"
authors = ["Tokio Contributors <team@tokio.rs>"]
license = "MIT"
edition = "2018"
publish = false

[dependencies]
tokio-test = { version = "0.2.0-alpha.5", path = "../../tokio-test" }
tokio-sync = { version = "0.2.0-alpha.5", path = ".." }

[[bin]]
name = "barrier"
path = "src/barrier.rs"

[[bin]]
name = "watch"
path = "src/watch.rs"

[[bin]]
name = "atomic_waker"
path = "src/atomic_waker.rs"
